server:
  port: 2333
  address: 0.0.0.0

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - ANDROID_TESTSUITE
      - IOS
      - ANDROID_VR
      - TVHTML5_SIMPLY_EMBEDDED_PLAYER
      - ANDROID_MUSIC

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:fb0eca58dde51169e9c1f4f44831386c4e175dbe"
      repository: "https://maven.lavalink.dev/snapshots"
  
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    bufferDurationMs: 800
    frameBufferDurationMs: 10000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

metrics:
  prometheus:
    enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG
